# Generated by Django 3.1.7 on 2021-03-28 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='reason',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='title',
        ),
    ]
