# Generated by Django 3.1.7 on 2021-03-28 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('closed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('theme', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default_group.jpg', upload_to='group_pictures')),
                ('admins', models.ManyToManyField(related_name='admin_mods', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='group_users', to=settings.AUTH_USER_MODEL)),
                ('mods', models.ManyToManyField(related_name='group_mods', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
